### ISSUE TITLE
iyzico-redirect

### ISSUE THREAD

**Issue by muhammetfaik** [codenteq/iyzico-payment-gateway#4]
İyzico redirec-page sayfası halen boş geliyor.

**Comment by ahmetarsiv** [comment]
Merhaba @muhammetfaik ,

Kurulum adımlarına göre ilerleme sağladığımda iyzico-redirect sayfasına yönlendirme yapıyor ve siparişi oluşturabiliyor. Lütfen kurulumu [Readme.md](https://github.com/codenteq/iyzico-payment-gateway/blob/master/README.md#3-installation) dosyasında göre ilerleyin.

![image](https://github.com/codenteq/iyzico-payment-gateway/assets/101526596/25ab1a88-d1f1-4372-90bf-82e0e0d7ab10)

**Comment by ahmetarsiv** [comment]
![image](https://github.com/codenteq/iyzico-payment-gateway/assets/101526596/3700a26d-3dc9-4f11-b534-14c0cacf4fd3)

**Comment by muhammetfaik** [comment]
Hallettim teşekkürler
