### ISSUE TITLE
Call to a member function toArray() on null

### ISSUE THREAD

**Issue by AlaaL** [codenteq/iyzico-payment-gateway#5]
Hi,
I am using bagisto 1.4.5 and your extension
after checkout and payment in iyzico sandbox, i get this error in the image below 

![image](https://github.com/codenteq/iyzico-payment-gateway/assets/5410074/b86e2cea-af48-4ffe-9a02-afe9160d8959)

**Comment by ahmetarsiv** [comment]
Hello @AlaaL, with the release of Bagisto v2.0, some routes have been updated. You need to update the `payment_methods` line to `paymentmethods` in the **src/Config/system.php** file. The same process should be applied to **src/Providers/IyzicoServiceProvider.php**, where you need to update the `payment_methods` line to paymentmethods.

> src/Config/system.php

```php
$this->mergeConfigFrom(
   +    'key'    => 'sales.paymentmethods.iyzico',
   -      'key'    => 'sales.payment_methods.iyzico',
);
```

> src/Providers/IyzicoServiceProvider.php

```php
$this->mergeConfigFrom(
   +    dirname(__DIR__) . '/Config/paymentmethods.php', 'paymentmethods'
   -     dirname(__DIR__) . '/Config/paymentmethods.php', 'payment_methods'
);
```

This method will work with your Bagisto version.
